#ifndef __MQTT_SERVER_SETTING_H__
#define __MQTT_SERVER_SETTING_H__

const char MQTT_SERVER_HOST_NAME[] = "atea1dy3lkg8s-ats.iot.us-east-2.amazonaws.com";
const char MQTT_CLIENT_ID[] = "STM32L475VGIOT01A";
const char MQTT_USERNAME[] = "STM32L4";
const char MQTT_PASSWORD[] = "";
const char MQTT_TOPIC_PUB[] = "pubtopic";
const char MQTT_TOPIC_SUB[] = "subtopic";


const int MQTT_SERVER_PORT = 8883;

/*
 * Root CA certificate here in PEM format.
 * "-----BEGIN CERTIFICATE-----\n"
 * ...
 * "-----END CERTIFICATE-----\n";
 */
/* Amazon Legacy Root CA */
/*const char* SSL_CA_PEM = "-----BEGIN CERTIFICATE-----\n"
"MIIE0zCCA7ugAwIBAgIQGNrRniZ96LtKIVjNzGs7SjANBgkqhkiG9w0BAQUFADCB\n"
"yjELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQL\n"
"ExZWZXJpU2lnbiBUcnVzdCBOZXR3b3JrMTowOAYDVQQLEzEoYykgMjAwNiBWZXJp\n"
"U2lnbiwgSW5jLiAtIEZvciBhdXRob3JpemVkIHVzZSBvbmx5MUUwQwYDVQQDEzxW\n"
"ZXJpU2lnbiBDbGFzcyAzIFB1YmxpYyBQcmltYXJ5IENlcnRpZmljYXRpb24gQXV0\n"
"aG9yaXR5IC0gRzUwHhcNMDYxMTA4MDAwMDAwWhcNMzYwNzE2MjM1OTU5WjCByjEL\n"
"MAkGA1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQLExZW\n"
"ZXJpU2lnbiBUcnVzdCBOZXR3b3JrMTowOAYDVQQLEzEoYykgMjAwNiBWZXJpU2ln\n"
"biwgSW5jLiAtIEZvciBhdXRob3JpemVkIHVzZSBvbmx5MUUwQwYDVQQDEzxWZXJp\n"
"U2lnbiBDbGFzcyAzIFB1YmxpYyBQcmltYXJ5IENlcnRpZmljYXRpb24gQXV0aG9y\n"
"aXR5IC0gRzUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCvJAgIKXo1\n"
"nmAMqudLO07cfLw8RRy7K+D+KQL5VwijZIUVJ/XxrcgxiV0i6CqqpkKzj/i5Vbex\n"
"t0uz/o9+B1fs70PbZmIVYc9gDaTY3vjgw2IIPVQT60nKWVSFJuUrjxuf6/WhkcIz\n"
"SdhDY2pSS9KP6HBRTdGJaXvHcPaz3BJ023tdS1bTlr8Vd6Gw9KIl8q8ckmcY5fQG\n"
"BO+QueQA5N06tRn/Arr0PO7gi+s3i+z016zy9vA9r911kTMZHRxAy3QkGSGT2RT+\n"
"rCpSx4/VBEnkjWNHiDxpg8v+R70rfk/Fla4OndTRQ8Bnc+MUCH7lP59zuDMKz10/\n"
"NIeWiu5T6CUVAgMBAAGjgbIwga8wDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8E\n"
"BAMCAQYwbQYIKwYBBQUHAQwEYTBfoV2gWzBZMFcwVRYJaW1hZ2UvZ2lmMCEwHzAH\n"
"BgUrDgMCGgQUj+XTGoasjY5rw8+AatRIGCx7GS4wJRYjaHR0cDovL2xvZ28udmVy\n"
"aXNpZ24uY29tL3ZzbG9nby5naWYwHQYDVR0OBBYEFH/TZafC3ey78DAJ80M5+gKv\n"
"MzEzMA0GCSqGSIb3DQEBBQUAA4IBAQCTJEowX2LP2BqYLz3q3JktvXf2pXkiOOzE\n"
"p6B4Eq1iDkVwZMXnl2YtmAl+X6/WzChl8gGqCBpH3vn5fJJaCGkgDdk+bW48DW7Y\n"
"5gaRQBi5+MHt39tBquCWIMnNZBU4gcmU7qKEKQsTb47bDN0lAtukixlE0kF6BWlK\n"
"WE9gyn6CagsCqiUXObXbf+eEZSqVir2G3l6BFoMtEMze/aiCKm0oHw0LxOXnGiYZ\n"
"4fQRbxC1lfznQgUy286dUV4otp6F01vvpX1FQHKOtw5rDgb7MzVIcbidJ4vEZV8N\n"
"hnacRHr2lVz2XTIIM6RUthg/aFzyQkqFOFSDX9HoLPKsEdao7WNq\n"
"-----END CERTIFICATE-----\n";*/

/* AmazonRootCA1.pem */
const char* SSL_CA_PEM = "-----BEGIN CERTIFICATE-----\n"
"MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF\n"
"ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6\n"
"b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL\n"
"MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv\n"
"b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj\n"
"ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM\n"
"9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw\n"
"IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6\n"
"VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L\n"
"93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm\n"
"jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC\n"
"AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA\n"
"A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI\n"
"U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs\n"
"N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv\n"
"o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU\n"
"5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy\n"
"rqXRfboQnoZsG4q5WTP468SQvvG5\n"
"-----END CERTIFICATE-----\n";

/*
 * (optional) Client certificate here in PEM format.
 * Set NULL if you don't use.
 * "-----BEGIN CERTIFICATE-----\n"
 * ...
 * "-----END CERTIFICATE-----\n";
 */
const char* SSL_CLIENT_CERT_PEM ="-----BEGIN CERTIFICATE-----\n"
"MIIDWTCCAkGgAwIBAgIUQAcNbH2be02BLSftW2v7I2qaykYwDQYJKoZIhvcNAQEL\n"
"BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g\n"
"SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIxMDIyODE0NTgx\n"
"NloXDTQ5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTQVdTIElvVCBDZXJ0aWZpY2F0\n"
"ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANHsNmwH5EueChMKHmCA\n"
"RXiohnBaJi+nN5moUWvLX97btzrRUrxXT9xqJ8yjpEYeiZ0joTWYKyqUrHi0wtoL\n"
"mqzbA7pbOlktyLUHuq4WIISMK0Yjf4EdG61XF6i3LXeHHROfpfWb9jbCV0WexUwl\n"
"pElsiO9VGIM8UCprpO1fvYY1FuuADnoeGeiFJLB/bNCTIYTfRsEW6/rleIolWVOt\n"
"AHtJJZvSbV9vRZNhMTKn6V1CrjAiY3OAYHVT1uSun+hq9h5ChZT0kxD9W7xzUlyj\n"
"cZOe3jMcIfj2y5ztGdmexE2eQ2L4zJhecRTeX5UtRvcVE69pb6yBfeaynIZ/E1XH\n"
"8P8CAwEAAaNgMF4wHwYDVR0jBBgwFoAUHEwWwhyaHvzd2XESCS1DiHJO98UwHQYD\n"
"VR0OBBYEFOqEZQ7sfcKIWHcbcGuViBAVZKxRMAwGA1UdEwEB/wQCMAAwDgYDVR0P\n"
"AQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQCW30KOX2x7NMa5Oxw6gez80sjk\n"
"/FciW/BO/Jm40Yf5c6uHVLvAYQEUUyM4bBsf5tqF4LzDS4s4S7rlfXkFQY+mn0yW\n"
"Oz0w1A6e71ykox+0wjlVIyApiPgEuiRFWNjZUt10U2zCzWzjYeIiJH2zgCMHWOr5\n"
"HPwo6c0m2pCuRcNIYfmANWvyGdvbbpdsYKXCr5LDUja1xvEoYoPzsu7CBKC4pLz/\n"
"wArP7YmxTbRo1Tz3M5oozfnhlV2sS/s6Y6FHse72mzXuqgFHAFhgpVQJpevLz7p7\n"
"Fx0hyojHvDVlI+MfTT0lLEBDeYw8HuD+4+gZvQzdy9UA31BEo/Wyfa/+JAic\n"
"-----END CERTIFICATE-----\n";


/*
 * (optional) Client private key here in PEM format.
 * Set NULL if you don't use.
 * "-----BEGIN RSA PRIVATE KEY-----\n"
 * ...
 * "-----END RSA PRIVATE KEY-----\n";
 */
const char* SSL_CLIENT_PRIVATE_KEY_PEM = "-----BEGIN RSA PRIVATE KEY-----\n"
"MIIEowIBAAKCAQEA0ew2bAfkS54KEwoeYIBFeKiGcFomL6c3mahRa8tf3tu3OtFS\n"
"vFdP3GonzKOkRh6JnSOhNZgrKpSseLTC2guarNsDuls6WS3ItQe6rhYghIwrRiN/\n"
"gR0brVcXqLctd4cdE5+l9Zv2NsJXRZ7FTCWkSWyI71UYgzxQKmuk7V+9hjUW64AO\n"
"eh4Z6IUksH9s0JMhhN9GwRbr+uV4iiVZU60Ae0klm9JtX29Fk2ExMqfpXUKuMCJj\n"
"c4BgdVPW5K6f6Gr2HkKFlPSTEP1bvHNSXKNxk57eMxwh+PbLnO0Z2Z7ETZ5DYvjM\n"
"mF5xFN5flS1G9xUTr2lvrIF95rKchn8TVcfw/wIDAQABAoIBADOpv6cMtinKBk6z\n"
"QdCcIPzV9Og3t4gozi052HgAAGM3jbujAoqprlTfp1XcvDQpldKfjzBCd/Uty9iV\n"
"HBNPocyCxkMZ6p1CAFBVS6NGfNBCMvA7EkkzYbliYsc59a2iCgznUI/Gx2yonZPb\n"
"xFC+PtV3KahFOBgsQsp93YQx+NHLUtFtKlUjKs7iF9TnRpImTXcjzfAnnSlJFbtT\n"
"lbjv5PqI78yMzvl/GC/C8Z5RHBGB670Ci9WHG1QHGArVzxcJ7iFtERvpvPhvPNQg\n"
"POhlCXuKuuNWQ07sY4F9dQtataaEXmrgeV9AIwIP+vhRq1WbsXTi86wcFdnyK03S\n"
"K3VSk4ECgYEA8yV1+icwshJou/QMIYTffEIaSU6jaAdkic4PMRCKQH+AWDRbiOL5\n"
"aCrxg6i5FqZ5drGZKqOrUGkdBJoz+MZVzq7lVNkBEP4bgoJAT8udrluTHHvoX8bo\n"
"tWrxUTzb66XODgCKJ/NRg3OaEIopx9Hf5il+fSjnsgYMpBtoBZh3vz8CgYEA3QUh\n"
"hrV4CGWksN/kEsC2XaOh2R3cRA1OwsM9ZGShvk9mS5Q+4z5J32TtLAjlySpFZUlD\n"
"1PWwIXka/yV72C4dAgz8bQxYcLDuv5KGq8SntPTnYxXkb5AR46D+PD47MB9opQIz\n"
"qKIK6Iw4f9xS6PGjmTi1sBKgo0rQ5nebBnJJHkECgYA5uJznQ8J1o5UleWwf0PFV\n"
"CERBPt/f5FFjvX0xwqFvalVHmzZXqrpWlks7XCSEUgTnvoWD79LNhgaTfx/zYPIh\n"
"3Lcoi1OLeyeAtfcaelX2fFrSGkAx7IB2AOtEw9PZf0UJYetqTIL/V8QtRP9iJlqm\n"
"wxb6E2ndgz4g/ziUi3tx9QKBgA+UqQRiDpAo+i8t2VopE7IOMv6nSDvT5FV+hflp\n"
"zq0n08JINRa38WU6LC4Kgohn3nSBcbK1jzEM5IZQEibvOURHvhPB5woqrun6XlwF\n"
"hP0Qtq8Zf/0NXvV5B/MfP/Togev/97xPkA1MtT7uPToGrs3CXayH46MfRxK4I8mU\n"
"jOsBAoGBAJHwOej+bJCExze8eoG+GkUhhfSB/Dto0HEiILclJcscBuuSm/AKcQ+1\n"
"sm/kzdXwZWH1GY0IX4rc07dClztqJolbaX24SFCkJwulNas6Hf/SpniicS15fRuT\n"
"BeberoBfXH7jqwuklEQbok9WhE8BA/uy7PITPHETlAGT4F4+X0XE\n"
"-----END RSA PRIVATE KEY-----\n";
#endif /* __MQTT_SERVER_SETTING_H__ */